In [1]:
import pandas as pd
import numpy as np
import os

In [33]:
file_path = '2020_RDFWFV_20201029_V08.xlsx'

# file_path에 따라 변수 결정 (N형만 생각)

if file_path == '2020_LER_20200804_V006.xlsx':
    num_input = 5
    num_output = 6
    num_in_cycle = 50
    num_of_cycle = 100
    num_total = num_in_cycle * num_of_cycle
    num_train = 75
    num_val = 10
    num_test = 15
    x_cols = "B:G"
    y_cols = "H:P"
    header = 0

elif file_path == '2020_LER_20201008_V008.xlsx':
    num_input = 5
    num_output = 6
    num_in_cycle = 50
    num_of_cycle = 127
    num_total = num_in_cycle * num_of_cycle
    num_train = 75
    num_val = 10
    num_test = 0
    x_cols = "D:F"
    y_cols = "H:P"
    header = 0
    
elif file_path == '2020_LER_20200922_testset.xlsx':
    num_input = 5
    num_output = 6
    num_in_cycle = [232, 289, 277, 253, 255]
    num_of_cycle = 5
    num_total = sum(num_in_cycle)
    x_cols = "D:F"
    y_cols = "H:P"
    header = 0
    
elif file_path == '2020_LER_20201021_testset.xlsx':
    num_input = 5
    num_output = 6
    num_in_cycle = [232, 289, 277, 253, 255, 250, 250, 250]
    num_of_cycle = 8
    num_total = sum(num_in_cycle)
    x_cols = "D:F"
    y_cols = "H:P"
    header = 0
    
elif file_path == '2020_RDFWFV_20201029_V08.xlsx':
    num_input = [5, 6, 6] # RDF, WFV, RDF+WFV
    num_output = 6
    num_in_cycle_train = 50
    num_in_cycle_test = 250
    num_of_cycle_train = [50, 50, 100]
    num_of_cycle_test = [2, 0, 2]
    num_total_train = [x*num_in_cycle_train for x in num_of_cycle_train]
    num_total_test = [x*num_in_cycle_test for x in num_of_cycle_test]
    header = 0

# 2020_LER_20200804_V006

In [75]:
# file_path version : 2020_LER_20200804_V006.xlsx

data_x = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=x_cols, nrows=2*num_total+1, header=header)
data_y = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=y_cols, nrows=2*num_total+1, header=header)

# one-hot encoding
X_all , Y_all = np.zeros((num_total, num_input)), np.zeros((num_total, num_output))
X_per_cycle, Y_per_cycle = np.zeros((num_of_cycle, num_input)), np.zeros((num_of_cycle, num_output))

# DATA_X DATA_Y preprocessing
# 1. N, P to 10, 01 (one-hot encoding)
data_x =pd.get_dummies(data_x, columns=['PNMOS'], dtype=float)

# 2. Remove unrequired column ( Wfin [nm], alpha )
# X: Wfin, alpha
data_x = data_x.drop('Wfin [nm]', axis=1)
data_x = data_x.drop('alpha', axis=1)

# Y: IDLO, IDHI, DIBL
data_y = data_y.drop('IDLO', axis=1)
data_y = data_y.drop('IDHI', axis=1)
data_y = data_y.drop('DIBL(mV)', axis=1)

# print(data_y)

# PANDAS TO NUMPY
# X_per_cycle
for i in range(num_of_cycle):
#     print(2*i*num_in_cycle, 2*i*num_in_cycle+1)
    X_per_cycle[i] = data_x[2*i*num_in_cycle:2*i*num_in_cycle+1].values
#     print(X_per_cycle[i])

# X_all
X_all = np.repeat(X_per_cycle,num_in_cycle,axis=0)

# Y_all
for i in range(num_of_cycle):
#     print(i*num_in_cycle,(i+1)*num_in_cycle)
    Y_all[i*num_in_cycle:i*num_in_cycle+num_in_cycle] = data_y[2*i*num_in_cycle:2*i*num_in_cycle + num_in_cycle].values
#     print(Y_all[i*num_in_cycle])

# Y_per_cycle    
for i in range(num_of_cycle):
    Y_per_cycle[i] = np.mean(Y_all[i*num_in_cycle:(i+1)*num_in_cycle],axis=0)

print("============ Data load =============")

print("X data shape: ", X_all.shape, "X per cycle data shape:", X_per_cycle.shape)
print("Y data shape: ", Y_all.shape, "Y per cycle data shape:", Y_per_cycle.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all)))

print("============ Data save =============")
data = []
data.append(X_all)
data.append(Y_all)
data.append(X_per_cycle)
data.append(Y_per_cycle)
    
data = np.array(data)
print("saved data shape: ", data.shape)
np.save('./'+file_path, data)

============ Data load =============
X data shape:  (5000, 5) X per cycle data shape: (100, 5)
Y data shape:  (5000, 6) Y per cycle data shape: (100, 6)
any nan in X?:  []
any nan in Y?:  []
============ Data save =============
saved data shape:  (4,)


In [79]:
# 검증의 시간

data = np.load(file_path+'.npy', allow_pickle=True)
    
X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

ㅔ갸ㅜ
for i in range(X_per_cycle.shape[0]):
    print(i)
    print(X_per_cycle[i])

(5000, 5) (5000, 6) (100, 5) (100, 6)
0
[  0.19316255  61.00227254 110.61789695   1.           0.        ]
1
[  0.71479321  30.46485839 164.03098759   1.           0.        ]
2
[  0.36639042  45.71598335 128.60254701   1.           0.        ]
3
[ 0.19156989 92.07622363 49.23479694  1.          0.        ]
4
[  0.64566003  28.77580661 181.68354021   1.           0.        ]
5
[  0.24976869  49.66628494 160.81107576   1.           0.        ]
6
[  0.58558021  33.64448087 197.99245715   1.           0.        ]
7
[ 0.6574629  45.59676738 70.67648175  1.          0.        ]
8
[ 0.13748646 47.26343432 23.46686409  1.          0.        ]
9
[  0.76475293  92.24596085 177.48935442   1.           0.        ]
10
[  0.29626603  81.48909977 179.64037297   1.           0.        ]
11
[ 0.6236913  87.47656503 97.32992467  1.          0.        ]
12
[  0.46475666  46.051489   122.05853503   1.           0.        ]
13
[  0.57950422  29.18162993 132.20992165   1.           0.        ]
14
[ 0.19323

# 2020_LER_20201008_V008

In [62]:
# file_path version : 2020_LER_20201008_V006.xlsx

data_x = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=x_cols, nrows=num_total+1, header=header)
data_y = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=y_cols, nrows=num_total+1, header=header)

# one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all , Y_all = np.zeros((num_total, num_input-2)), np.zeros((num_total, num_output))
X_per_cycle, Y_per_cycle = np.zeros((num_of_cycle, num_input-2)), np.zeros((num_of_cycle, num_output))

# DATA_X DATA_Y preprocessing

# Y: IDLO, IDHI, DIBL
data_y = data_y.drop('IDLO', axis=1)
data_y = data_y.drop('IDHI', axis=1)
data_y = data_y.drop('DIBL(mV)', axis=1)
print(data_x)
# print(data_y)

# PANDAS TO NUMPY
# X_per_cycle
for i in range(num_of_cycle):
#     print(i*num_in_cycle, i*num_in_cycle+1)
    X_per_cycle[i] = data_x[i*num_in_cycle:i*num_in_cycle+1].values
#     print(X_per_cycle[i])

# X_all
X_all = np.repeat(X_per_cycle,num_in_cycle,axis=0)


# 인위적으로 one-hot 넣어주기

X_all = np.hstack((X_all, np.ones((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.ones((X_per_cycle.shape[0], 1))))

X_all = np.hstack((X_all, np.zeros((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.zeros((X_per_cycle.shape[0], 1))))


# Y_all
for i in range(num_of_cycle):
#     print(i*num_in_cycle,(i+1)*num_in_cycle)
    Y_all[i*num_in_cycle:(i+1)*num_in_cycle] = data_y[i*num_in_cycle:(i+1)*num_in_cycle].values
#     print(Y_all[i*num_in_cycle])

# Y_per_cycle    
for i in range(num_of_cycle):
    Y_per_cycle[i] = np.mean(Y_all[i*num_in_cycle:(i+1)*num_in_cycle],axis=0)

print("============ Data load =============")

print("X data shape: ", X_all.shape, "X per cycle data shape:", X_per_cycle.shape)
print("Y data shape: ", Y_all.shape, "Y per cycle data shape:", Y_per_cycle.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all)))

print("============ Data save =============")
data = []
data.append(X_all)
data.append(Y_all)
data.append(X_per_cycle)
data.append(Y_per_cycle)
    
data = np.array(data)
print("saved data shape: ", data.shape)
np.save('./'+file_path, data)

          amp.     corr.x      corr.y
0     0.193163  61.002273  110.617897
1          NaN        NaN         NaN
2          NaN        NaN         NaN
3          NaN        NaN         NaN
4          NaN        NaN         NaN
...        ...        ...         ...
6345       NaN        NaN         NaN
6346       NaN        NaN         NaN
6347       NaN        NaN         NaN
6348       NaN        NaN         NaN
6349       NaN        NaN         NaN

[6350 rows x 3 columns]
============ Data load =============
X data shape:  (6350, 5) X per cycle data shape: (127, 5)
Y data shape:  (6350, 6) Y per cycle data shape: (127, 6)
any nan in X?:  []
any nan in Y?:  []
============ Data save =============
saved data shape:  (4,)


In [64]:
# 검증의 시간

data = np.load(file_path+'.npy', allow_pickle=True)
    
X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

for i in range(Y_all.shape[0]):
    print(X_per_cycle[i])

(6350, 5) (6350, 6) (127, 5) (127, 6)
[  0.19316255  61.00227254 110.61789695   1.           0.        ]
[  0.71479321  30.46485839 164.03098759   1.           0.        ]
[  0.36639042  45.71598335 128.60254701   1.           0.        ]
[ 0.19156989 92.07622363 49.23479694  1.          0.        ]
[  0.64566003  28.77580661 181.68354021   1.           0.        ]
[  0.24976869  49.66628494 160.81107576   1.           0.        ]
[  0.58558021  33.64448087 197.99245715   1.           0.        ]
[ 0.6574629  45.59676738 70.67648175  1.          0.        ]
[ 0.13748646 47.26343432 23.46686409  1.          0.        ]
[  0.76475293  92.24596085 177.48935442   1.           0.        ]
[  0.29626603  81.48909977 179.64037297   1.           0.        ]
[ 0.6236913  87.47656503 97.32992467  1.          0.        ]
[  0.46475666  46.051489   122.05853503   1.           0.        ]
[  0.57950422  29.18162993 132.20992165   1.           0.        ]
[ 0.19323371 43.90356688 60.43297631  1.    

IndexError: index 127 is out of bounds for axis 0 with size 127

# 2020_LER_0922_testset

In [98]:
# file_path version : 2020_LER_20201008_V006.xlsx

file_path = '2020_LER_20200922_testset.xlsx'

data_x = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=x_cols, nrows=num_total+1, header=header)
data_y = pd.read_excel('../'+file_path, sheet_name='Generated DATAs', usecols=y_cols, nrows=num_total+1, header=header)

# one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all , Y_all = np.zeros((num_total, num_input-2)), np.zeros((num_total, num_output))
X_per_cycle, Y_per_cycle = np.zeros((num_of_cycle, num_input-2)), np.zeros((num_of_cycle, num_output))

# DATA_X DATA_Y preprocessing

# Y: IDLO, IDHI, DIBL
data_y = data_y.drop('IDLO', axis=1)
data_y = data_y.drop('IDHI', axis=1)
data_y = data_y.drop('DIBL(mV)', axis=1)
print(data_x)
# print(data_y)

X_all = data_x.values
Y_all = data_y.values

# X_per_cycle

idx = 0
add = 0
for i in range(num_of_cycle):
    add = num_in_cycle[i]
            
    X_per_cycle[i] = X_all[idx:idx+1]
    Y_per_cycle[i] = np.mean(Y_all[idx:idx+add], axis=0)
            
    temp = X_per_cycle[i].reshape(1, num_input-2)
            
    X_all[idx:idx+add] = np.repeat(temp, add, axis=0)
    idx += add
    
# 인위적으로 one-hot 넣어주기

X_all = np.hstack((X_all, np.ones((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.ones((X_per_cycle.shape[0], 1))))

X_all = np.hstack((X_all, np.zeros((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.zeros((X_per_cycle.shape[0], 1))))

print("============ Data load =============")

print("X data shape: ", X_all.shape, "X per cycle data shape:", X_per_cycle.shape)
print("Y data shape: ", Y_all.shape, "Y per cycle data shape:", Y_per_cycle.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all)))  

print("============ Data save =============")
    
data = []
data.append(X_all)
data.append(Y_all)
data.append(X_per_cycle)
data.append(Y_per_cycle)
    
data = np.array(data)
print("saved data shape: ", data.shape)
np.save('./'+file_path, data)

          amp.     corr.x      corr.y
0     0.624847  17.007432  173.857189
1          NaN        NaN         NaN
2          NaN        NaN         NaN
3          NaN        NaN         NaN
4          NaN        NaN         NaN
...        ...        ...         ...
1301       NaN        NaN         NaN
1302       NaN        NaN         NaN
1303       NaN        NaN         NaN
1304       NaN        NaN         NaN
1305       NaN        NaN         NaN

[1306 rows x 3 columns]
============ Data load =============
X data shape:  (1306, 5) X per cycle data shape: (5, 5)
Y data shape:  (1306, 6) Y per cycle data shape: (5, 6)
any nan in X?:  []
any nan in Y?:  []
============ Data save =============
saved data shape:  (4,)


In [99]:
# 검증의 시간

data = np.load(file_path+'.npy', allow_pickle=True)
    
X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

for i in range(Y_all.shape[0]):
    print(Y_all[i])

(1306, 5) (1306, 6) (5, 5) (5, 6)
[1.9580e-12 4.2420e-05 1.6180e-05 3.4300e-01 3.5300e-01 6.1501e+01]
[6.1350e-13 3.6300e-05 1.4500e-05 3.7000e-01 3.7700e-01 6.0804e+01]
[7.437e-13 3.182e-05 1.391e-05 3.700e-01 3.740e-01 6.120e+01]
[1.4790e-12 4.1000e-05 1.5990e-05 3.5200e-01 3.5800e-01 6.1429e+01]
[1.9260e-12 4.3930e-05 1.7650e-05 3.4400e-01 3.5300e-01 6.1569e+01]
[1.1990e-12 3.6920e-05 1.4540e-05 3.5600e-01 3.6300e-01 6.1272e+01]
[1.6050e-12 3.6600e-05 1.3990e-05 3.4900e-01 3.5500e-01 6.1348e+01]
[1.5290e-12 4.0250e-05 1.5810e-05 3.5000e-01 3.5700e-01 6.1406e+01]
[2.2580e-12 3.9540e-05 1.6170e-05 3.4200e-01 3.5100e-01 6.1827e+01]
[1.9230e-12 4.2050e-05 1.5870e-05 3.4500e-01 3.5300e-01 6.1627e+01]
[1.1800e-12 4.0380e-05 1.7000e-05 3.5500e-01 3.6300e-01 6.1232e+01]
[2.461e-12 4.101e-05 1.478e-05 3.390e-01 3.490e-01 6.173e+01]
[3.8970e-12 4.2100e-05 1.6900e-05 3.3100e-01 3.4100e-01 6.2348e+01]
[2.6110e-12 4.3680e-05 1.6380e-05 3.3700e-01 3.4800e-01 6.1783e+01]
[2.5380e-12 4.2210e-05 1.6

[1.9460e-12 4.2370e-05 1.6740e-05 3.4400e-01 3.5200e-01 6.1528e+01]
[2.8210e-12 4.3190e-05 1.6510e-05 3.3700e-01 3.4500e-01 6.1912e+01]
[1.2100e-12 4.0100e-05 1.5840e-05 3.5500e-01 3.6100e-01 6.1229e+01]
[1.1900e-12 3.9310e-05 1.5080e-05 3.5500e-01 3.6200e-01 6.1208e+01]
[1.5130e-12 3.9020e-05 1.6100e-05 3.5100e-01 3.5700e-01 6.1536e+01]
[3.7450e-12 4.3600e-05 1.7810e-05 3.3200e-01 3.4100e-01 6.2351e+01]
[4.030e-12 4.368e-05 1.739e-05 3.310e-01 3.410e-01 6.256e+01]
[3.539e-12 4.400e-05 1.725e-05 3.320e-01 3.430e-01 6.221e+01]
[1.4000e-12 4.0690e-05 1.4720e-05 3.5100e-01 3.5900e-01 6.1247e+01]
[2.2210e-12 4.1420e-05 1.7000e-05 3.4300e-01 3.4900e-01 6.1841e+01]
[2.000e-12 4.265e-05 1.691e-05 3.430e-01 3.510e-01 6.155e+01]
[1.9700e-12 4.1760e-05 1.5860e-05 3.4500e-01 3.5200e-01 6.1595e+01]
[2.064e-12 4.240e-05 1.687e-05 3.440e-01 3.510e-01 6.173e+01]
[2.2890e-12 4.0890e-05 1.5820e-05 3.4000e-01 3.4800e-01 6.1602e+01]
[1.2440e-12 3.4430e-05 1.4750e-05 3.5500e-01 3.6100e-01 6.1226e+01]
[1.9

 # 2020_LER_1021_testset

In [10]:
# file_path version : 2020_LER_20201008_V006.xlsx

print(num_total)
file_path = '2020_LER_20201021_testset.xlsx'

data_x = pd.read_excel('../'+file_path, sheet_name='Generated Datas', usecols=x_cols, nrows=num_total+1, header=header)
data_y = pd.read_excel('../'+file_path, sheet_name='Generated Datas', usecols=y_cols, nrows=num_total+1, header=header)

# one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all , Y_all = np.zeros((num_total, num_input-2)), np.zeros((num_total, num_output))
X_per_cycle, Y_per_cycle = np.zeros((num_of_cycle, num_input-2)), np.zeros((num_of_cycle, num_output))

# DATA_X DATA_Y preprocessing

# Y: IDLO, IDHI, DIBL
data_y = data_y.drop('IDLO', axis=1)
data_y = data_y.drop('IDHI', axis=1)
data_y = data_y.drop('DIBL(mV)', axis=1)
print(data_x)
# print(data_y)

X_all = data_x.values
Y_all = data_y.values

# X_per_cycle

idx = 0
add = 0
for i in range(num_of_cycle):
    add = num_in_cycle[i]
            
    X_per_cycle[i] = X_all[idx:idx+1]
    Y_per_cycle[i] = np.mean(Y_all[idx:idx+add], axis=0)
            
    temp = X_per_cycle[i].reshape(1, num_input-2)
            
    X_all[idx:idx+add] = np.repeat(temp, add, axis=0)
    idx += add
    
# 인위적으로 one-hot 넣어주기

X_all = np.hstack((X_all, np.ones((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.ones((X_per_cycle.shape[0], 1))))

X_all = np.hstack((X_all, np.zeros((X_all.shape[0], 1))))
X_per_cycle = np.hstack((X_per_cycle, np.zeros((X_per_cycle.shape[0], 1))))

print("============ Data load =============")

print("X data shape: ", X_all.shape, "X per cycle data shape:", X_per_cycle.shape)
print("Y data shape: ", Y_all.shape, "Y per cycle data shape:", Y_per_cycle.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all)))  

print("============ Data save =============")
    
data = []
data.append(X_all)
data.append(Y_all)
data.append(X_per_cycle)
data.append(Y_per_cycle)
    
data = np.array(data)
print("saved data shape: ", data.shape)
np.save('./'+file_path, data)

2056
          amp.     corr.x      corr.y
0     0.624847  17.007432  173.857189
1          NaN        NaN         NaN
2          NaN        NaN         NaN
3          NaN        NaN         NaN
4          NaN        NaN         NaN
...        ...        ...         ...
2051       NaN        NaN         NaN
2052       NaN        NaN         NaN
2053       NaN        NaN         NaN
2054       NaN        NaN         NaN
2055       NaN        NaN         NaN

[2056 rows x 3 columns]
============ Data load =============
X data shape:  (2056, 5) X per cycle data shape: (8, 5)
Y data shape:  (2056, 6) Y per cycle data shape: (8, 6)
any nan in X?:  []
any nan in Y?:  []
============ Data save =============
saved data shape:  (4,)


In [19]:
# 검증의 시간

data = np.load(file_path+'.npy', allow_pickle=True)
    
X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)


#print(Y_all[])

for i in range(1306, 1556):
    print(Y_all[i])
#print(Y_all[1306:1556])

total_sum = 0
for i in [232, 289, 277, 253, 255, 250, 250, 250]:
    total_sum += i
    print(total_sum)
    
# for i in range(Y_all.shape[0]):
#     if 
#     print(Y_all[i])

(2056, 5) (2056, 6) (8, 5) (8, 6)
[2.0210e-12 4.2070e-05 1.6100e-05 3.4300e-01 3.5000e-01 6.1526e+01]
[1.7980e-12 4.2010e-05 1.6180e-05 3.4500e-01 3.5300e-01 6.1443e+01]
[1.7630e-12 4.2270e-05 1.6260e-05 3.4600e-01 3.5300e-01 6.1426e+01]
[2.1660e-12 4.2790e-05 1.6390e-05 3.4100e-01 3.4900e-01 6.1548e+01]
[2.4170e-12 4.3730e-05 1.7310e-05 3.4000e-01 3.4700e-01 6.1766e+01]
[2.1470e-12 4.2130e-05 1.6300e-05 3.4200e-01 3.4900e-01 6.1609e+01]
[2.3030e-12 4.2860e-05 1.6450e-05 3.4100e-01 3.4800e-01 6.1703e+01]
[1.9840e-12 4.2930e-05 1.6300e-05 3.4300e-01 3.5100e-01 6.1494e+01]
[2.6190e-12 4.2340e-05 1.6540e-05 3.3800e-01 3.4600e-01 6.1756e+01]
[1.8640e-12 4.2090e-05 1.5910e-05 3.4400e-01 3.5200e-01 6.1399e+01]
[2.0250e-12 4.2800e-05 1.6540e-05 3.4300e-01 3.5000e-01 6.1619e+01]
[2.3020e-12 4.2440e-05 1.6790e-05 3.4100e-01 3.4800e-01 6.1707e+01]
[1.7970e-12 4.2450e-05 1.6290e-05 3.4500e-01 3.5300e-01 6.1464e+01]
[2.2230e-12 4.2590e-05 1.6600e-05 3.4100e-01 3.4800e-01 6.1671e+01]
[2.3430e-12 4.

# 2020_RDFWFV_20201029_V08

### 1. RDF ( train + test )

In [70]:
# file_path == '2020_RDFWFV_20201029_V08.xlsx':
#     num_input = [5, 6, 6] # RDF, WFV, RDF+WFV
#     num_output = 6
#     num_in_cycle_train = 50
#     num_in_cycle_test = 250
#     num_of_cycle_train = [50, 50, 100]
#     num_of_cycle_test = [2, 0, 2]
#     num_total_train = [x*num_in_cycle_train for x in num_of_cycle_train]
#     num_total_test = [x*num_in_cycle_test for x in num_of_cycle_test]
#     header = 0

file_path = '2020_RDFWFV_20201029_V08.xlsx'

#### TRAIN

## 1.read from excel
train_data_x = pd.read_excel('../'+file_path, sheet_name='RDF data', usecols="C:E", nrows=num_total_train[0]+1, header=header)
train_data_y = pd.read_excel('../'+file_path, sheet_name='RDF data', usecols="F:M", nrows=num_total_train[0]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_train , Y_all_train = np.zeros((num_total_train[0], num_input[0]-2)), np.zeros((num_total_train[0], num_output))
X_per_cycle_train, Y_per_cycle_train = np.zeros((num_of_cycle_train[0], num_input[0]-2)), np.zeros((num_of_cycle_train[0], num_output))

## 3. DATA_X DATA_Y preprocessing
# Y: IDLO, IDHI
train_data_y = train_data_y.drop('Idlo', axis=1)
train_data_y = train_data_y.drop('Idhi', axis=1)

## 4. X_per_cycle
for i in range(num_of_cycle_train[0]):
#     print(i*num_in_cycle_train, i*num_in_cycle_train+1)
    X_per_cycle_train[i] = train_data_x[i*num_in_cycle_train:i*num_in_cycle_train+1].values
#     print(X_per_cycle_train[i])

## 5. X_all
X_all_train = np.repeat(X_per_cycle_train,num_in_cycle_train,axis=0)


## 6. 인위적으로 one-hot 넣어주기
X_all_train = np.hstack((X_all_train, np.ones((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.ones((X_per_cycle_train.shape[0], 1))))

X_all_train = np.hstack((X_all_train, np.zeros((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.zeros((X_per_cycle_train.shape[0], 1))))


## 7. Y_all
for i in range(num_of_cycle_train[0]):
#     print(i*num_in_cycle_train,(i+1)*num_in_cycle_train)
    Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train] = train_data_y[i*num_in_cycle_train:(i+1)*num_in_cycle_train].values
#     print(Y_all_train[i*num_in_cycle_train])

## 8. Y_per_cycle    
for i in range(num_of_cycle_train[0]):
    Y_per_cycle_train[i] = np.mean(Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train],axis=0)
#     print(i, Y_per_cycle_train[i])

print("============ TRAIN Data load =============")
print()
print("X data shape: ", X_all_train.shape, "X per cycle data shape:", X_per_cycle_train.shape)
print("Y data shape: ", Y_all_train.shape, "Y per cycle data shape:", Y_per_cycle_train.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_train)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_train)))  
print()
print("============ TRAIN Data save =============")
print()
data_train = []
data_train.append(X_all_train)
data_train.append(Y_all_train)
data_train.append(X_per_cycle_train)
data_train.append(Y_per_cycle_train)
    
data_train = np.array(data_train)
print("saved data shape: ", data_train.shape)
np.save('./rdf_train'+file_path, data_train)
print()

#### TEST

## 1.read from excel
test_data_x = pd.read_excel('../'+file_path, sheet_name='RDF testdata', usecols="B:D", nrows=num_total_test[0]+1, header=header)
test_data_y = pd.read_excel('../'+file_path, sheet_name='RDF testdata', usecols="E:L", nrows=num_total_test[0]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_test , Y_all_test = np.zeros((num_total_test[0], num_input[0]-2)), np.zeros((num_total_test[0], num_output))
X_per_cycle_test, Y_per_cycle_test = np.zeros((num_of_cycle_test[0], num_input[0]-2)), np.zeros((num_of_cycle_test[0], num_output))

## 3. DATA_X DATA_Y preprocessing
test_data_y = test_data_y.drop('Idlo', axis=1)
test_data_y = test_data_y.drop('Idhi', axis=1)

## 4. X_per_cycle, Y_all
for i in range(num_of_cycle_test[0]):
    X_per_cycle_test[i] = test_data_x[i*num_in_cycle_test:i*num_in_cycle_test+1].values
    
Y_all_test = test_data_y.values    

## 5. X_all, Y_per_cycle
for i in range(num_of_cycle_test[0]):
#     print(i*num_in_cycle_test, (i+1)*num_in_cycle_test)
#     print(X_per_cycle_test[i])
#     print(np.reshape(X_per_cycle_test[i], (1,3)).shape)
    X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test] = np.repeat(np.reshape(X_per_cycle_test[i], (1,3)), num_in_cycle_test, axis=0)
#     print(X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test])

    Y_per_cycle_test[i] = np.mean(Y_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test], axis=0)

## 6. 인위적으로 one-hot 넣어주기
X_all_test = np.hstack((X_all_test, np.ones((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.ones((X_per_cycle_test.shape[0], 1))))

X_all_test = np.hstack((X_all_test, np.zeros((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.zeros((X_per_cycle_test.shape[0], 1))))    
    
# for i in range(X_all_test.shape[0]):
#     print(X_all_test[i])
#     print(Y_all_test[i])
    
    
print("============ TEST Data load =============")
print()
print("X data shape: ", X_all_test.shape, "X per cycle data shape:", X_per_cycle_test.shape)
print("Y data shape: ", Y_all_test.shape, "Y per cycle data shape:", Y_per_cycle_test.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_test)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_test)))  
print()
print("============ TRAIN Data save =============")
print()
data_test = []
data_test.append(X_all_test)
data_test.append(Y_all_test)
data_test.append(X_per_cycle_test)
data_test.append(Y_per_cycle_test)
    
data_test = np.array(data_test)
print("saved data shape: ", data_test.shape)
np.save('./rdf_test'+file_path, data_test)
print()

============ TRAIN Data load =============

X data shape:  (2500, 5) X per cycle data shape: (50, 5)
Y data shape:  (2500, 6) Y per cycle data shape: (50, 6)
any nan in X?:  []
any nan in Y?:  []

============ TRAIN Data save =============

saved data shape:  (4,)

============ TEST Data load =============

X data shape:  (500, 5) X per cycle data shape: (2, 5)
Y data shape:  (500, 6) Y per cycle data shape: (2, 6)
any nan in X?:  []
any nan in Y?:  []

============ TRAIN Data save =============

saved data shape:  (4,)



In [80]:
##### train
file_path = 'rdf_train2020_RDFWFV_20201029_V08.xlsx'

data = np.load(file_path+'.npy', allow_pickle=True)

X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

for i in range(Y_all.shape[0]):
    print(Y_all[i])

# test    
test_file_path = 'rdf_test2020_RDFWFV_20201029_V08.xlsx'

test_data = np.load(test_file_path+'.npy', allow_pickle=True)

test_X_all, test_Y_all, test_X_per_cycle, test_Y_per_cycle = test_data[0], test_data[1], test_data[2], test_data[3]

print(test_data[0].shape, test_data[1].shape, test_data[2].shape, test_data[3].shape)

for i in range(test_Y_all.shape[0]):
    print(test_Y_all[i])

(2500, 5) (2500, 6) (50, 5) (50, 6)
[2.1610e-12 3.4800e-01 3.4100e-01 7.3110e-06 2.1470e-05 6.1024e+01]
[2.1160e-12 3.4800e-01 3.4200e-01 7.7550e-06 2.3090e-05 6.1121e+01]
[2.1250e-12 3.4800e-01 3.4200e-01 7.7380e-06 2.1880e-05 6.1073e+01]
[2.318e-12 3.460e-01 3.400e-01 8.019e-06 2.576e-05 6.111e+01]
[2.1720e-12 3.4700e-01 3.4100e-01 7.8290e-06 2.1890e-05 6.0965e+01]
[2.0670e-12 3.4900e-01 3.4200e-01 7.3110e-06 2.2150e-05 6.0968e+01]
[2.1180e-12 3.4900e-01 3.4200e-01 7.5880e-06 2.2200e-05 6.1032e+01]
[2.0730e-12 3.4900e-01 3.4300e-01 7.6010e-06 2.0940e-05 6.1044e+01]
[2.1320e-12 3.4800e-01 3.4200e-01 7.9540e-06 2.1880e-05 6.1028e+01]
[2.2110e-12 3.4700e-01 3.4100e-01 7.4870e-06 2.2470e-05 6.1097e+01]
[2.031e-12 3.490e-01 3.430e-01 7.503e-06 2.091e-05 6.102e+01]
[2.2500e-12 3.4700e-01 3.4000e-01 7.9310e-06 2.3910e-05 6.1036e+01]
[1.978e-12 3.510e-01 3.440e-01 7.067e-06 1.963e-05 6.100e+01]
[2.1100e-12 3.4800e-01 3.4200e-01 7.4210e-06 2.2120e-05 6.0992e+01]
[2.0720e-12 3.4900e-01 3.4200e

[3.3200e-12 3.4100e-01 3.3200e-01 1.7060e-05 4.4550e-05 6.1966e+01]
[3.327e-12 3.410e-01 3.320e-01 1.735e-05 4.442e-05 6.202e+01]
[3.4250e-12 3.4000e-01 3.3100e-01 1.7570e-05 4.5870e-05 6.1902e+01]
[3.3590e-12 3.4000e-01 3.3200e-01 1.7350e-05 4.4300e-05 6.1953e+01]
[3.1660e-12 3.4100e-01 3.3300e-01 1.6790e-05 4.4050e-05 6.1941e+01]
[3.3140e-12 3.4000e-01 3.3200e-01 1.8400e-05 4.6890e-05 6.1896e+01]
[3.366e-12 3.400e-01 3.320e-01 1.739e-05 4.511e-05 6.193e+01]
[3.5010e-12 3.4000e-01 3.3100e-01 1.7260e-05 4.4660e-05 6.1974e+01]
[3.3970e-12 3.4000e-01 3.3200e-01 1.6940e-05 4.3720e-05 6.1895e+01]
[3.7220e-12 3.3900e-01 3.2900e-01 1.8860e-05 4.7810e-05 6.1977e+01]
[3.4180e-12 3.4000e-01 3.3200e-01 1.8150e-05 4.5180e-05 6.2025e+01]
[3.1700e-12 3.4200e-01 3.3300e-01 1.6750e-05 4.3040e-05 6.1921e+01]
[3.3730e-12 3.4000e-01 3.3200e-01 1.7560e-05 4.5100e-05 6.1985e+01]
[3.3930e-12 3.4000e-01 3.3200e-01 1.8150e-05 4.5880e-05 6.2023e+01]
[3.4750e-12 3.3900e-01 3.3100e-01 1.7540e-05 4.5550e-05 6.19

[4.1530e-12 3.3900e-01 3.2900e-01 2.5170e-05 5.4710e-05 6.2351e+01]
[3.6690e-12 3.4200e-01 3.3200e-01 2.1700e-05 4.8680e-05 6.2297e+01]
[4.1330e-12 3.4000e-01 3.2900e-01 2.4050e-05 5.3750e-05 6.2372e+01]
[3.9130e-12 3.4100e-01 3.3000e-01 2.2170e-05 5.0880e-05 6.2325e+01]
[3.968e-12 3.390e-01 3.300e-01 2.291e-05 5.114e-05 6.235e+01]
[3.8820e-12 3.4100e-01 3.3100e-01 2.3470e-05 5.2190e-05 6.2392e+01]
[3.8590e-12 3.4000e-01 3.3100e-01 2.2480e-05 4.9320e-05 6.2294e+01]
[4.0200e-12 3.4100e-01 3.2900e-01 2.3710e-05 5.3100e-05 6.2279e+01]
[3.9080e-12 3.4100e-01 3.3000e-01 2.3340e-05 5.2620e-05 6.2311e+01]
[3.7190e-12 3.4200e-01 3.3100e-01 2.2680e-05 5.0410e-05 6.2273e+01]
[3.7660e-12 3.4200e-01 3.3100e-01 2.2120e-05 4.9660e-05 6.2357e+01]
[4.1160e-12 3.4000e-01 3.2900e-01 2.4110e-05 5.2520e-05 6.2306e+01]
[3.7860e-12 3.4000e-01 3.3100e-01 2.2650e-05 5.0370e-05 6.2221e+01]
[3.8110e-12 3.4100e-01 3.3100e-01 2.2590e-05 5.1090e-05 6.2245e+01]
[4.075e-12 3.390e-01 3.290e-01 2.534e-05 5.402e-05 6.2

[2.1870e-12 3.4700e-01 3.4100e-01 8.4820e-06 2.5160e-05 6.1079e+01]
[2.1710e-12 3.4700e-01 3.4100e-01 8.7190e-06 2.6980e-05 6.1185e+01]
[2.0910e-12 3.4800e-01 3.4200e-01 8.2120e-06 2.1590e-05 6.1078e+01]
[2.0210e-12 3.4900e-01 3.4300e-01 8.4370e-06 2.2780e-05 6.1095e+01]
[2.1830e-12 3.4800e-01 3.4100e-01 8.8370e-06 2.5430e-05 6.1128e+01]
[2.1960e-12 3.4700e-01 3.4100e-01 8.3020e-06 2.7180e-05 6.1082e+01]
[2.1130e-12 3.4900e-01 3.4200e-01 8.2250e-06 2.1860e-05 6.1116e+01]
[2.1940e-12 3.4700e-01 3.4100e-01 8.8640e-06 2.5980e-05 6.1142e+01]
[2.1280e-12 3.4800e-01 3.4200e-01 8.7880e-06 2.4040e-05 6.1085e+01]
[2.0460e-12 3.4900e-01 3.4200e-01 8.3770e-06 2.3470e-05 6.1059e+01]
[2.1790e-12 3.4800e-01 3.4100e-01 8.3400e-06 2.4670e-05 6.1131e+01]
[2.1250e-12 3.4800e-01 3.4200e-01 8.5300e-06 2.4390e-05 6.1083e+01]
[2.1240e-12 3.4800e-01 3.4200e-01 8.4870e-06 2.4050e-05 6.1086e+01]
[2.0540e-12 3.4900e-01 3.4200e-01 8.6130e-06 2.6610e-05 6.1063e+01]
[2.043e-12 3.480e-01 3.430e-01 8.257e-06 2.345e-

### 2. WFV ( train + test )

In [81]:
# file_path == '2020_RDFWFV_20201029_V08.xlsx':
#     num_input = [5, 6, 6] # RDF, WFV, RDF+WFV
#     num_output = 6
#     num_in_cycle_train = 50
#     num_in_cycle_test = 250
#     num_of_cycle_train = [50, 50, 100]
#     num_of_cycle_test = [2, 0, 2]
#     num_total_train = [x*num_in_cycle_train for x in num_of_cycle_train]
#     num_total_test = [x*num_in_cycle_test for x in num_of_cycle_test]
#     header = 0
  
# # WFV

# file_path == '2020_RDFWFV_20201029_V08.xlsx':
#     num_input = [5, 6, 6] # RDF, WFV, RDF+WFV
#     num_output = 6
#     num_in_cycle_train = 50
#     num_in_cycle_test = 250
#     num_of_cycle_train = [50, 50, 100]
#     num_of_cycle_test = [2, 0, 2]
#     num_total_train = [x*num_in_cycle_train for x in num_of_cycle_train]
#     num_total_test = [x*num_in_cycle_test for x in num_of_cycle_test]
#     header = 0

file_path = '2020_RDFWFV_20201029_V08.xlsx'

#### TRAIN

## 1.read from excel
train_data_x = pd.read_excel('../'+file_path, sheet_name='WFV data', usecols="C:F", nrows=num_total_train[1]+1, header=header)
train_data_y = pd.read_excel('../'+file_path, sheet_name='WFV data', usecols="G:N", nrows=num_total_train[1]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_train , Y_all_train = np.zeros((num_total_train[1], num_input[1]-2)), np.zeros((num_total_train[1], num_output))
X_per_cycle_train, Y_per_cycle_train = np.zeros((num_of_cycle_train[1], num_input[1]-2)), np.zeros((num_of_cycle_train[1], num_output))

## 3. DATA_X DATA_Y preprocessing
# Y: IDLO, IDHI
train_data_y = train_data_y.drop('Idlo', axis=1)
train_data_y = train_data_y.drop('Idhi', axis=1)

print(train_data_y)

## 4. X_per_cycle
for i in range(num_of_cycle_train[1]):
#     print(i*num_in_cycle_train, i*num_in_cycle_train+1)
    X_per_cycle_train[i] = train_data_x[i*num_in_cycle_train:i*num_in_cycle_train+1].values
#     print(X_per_cycle_train[i])

## 5. X_all
X_all_train = np.repeat(X_per_cycle_train,num_in_cycle_train,axis=0)


## 6. 인위적으로 one-hot 넣어주기
X_all_train = np.hstack((X_all_train, np.ones((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.ones((X_per_cycle_train.shape[0], 1))))

X_all_train = np.hstack((X_all_train, np.zeros((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.zeros((X_per_cycle_train.shape[0], 1))))


## 7. Y_all
for i in range(num_of_cycle_train[1]):
#     print(i*num_in_cycle_train,(i+1)*num_in_cycle_train)
    Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train] = train_data_y[i*num_in_cycle_train:(i+1)*num_in_cycle_train].values
#     print(Y_all_train[i*num_in_cycle_train])

## 8. Y_per_cycle    
for i in range(num_of_cycle_train[1]):
    Y_per_cycle_train[i] = np.mean(Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train],axis=0)
#     print(i, Y_per_cycle_train[i])

print("============ TRAIN Data load =============")
print()
print("X data shape: ", X_all_train.shape, "X per cycle data shape:", X_per_cycle_train.shape)
print("Y data shape: ", Y_all_train.shape, "Y per cycle data shape:", Y_per_cycle_train.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_train)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_train)))  
print()
print("============ TRAIN Data save =============")
print()
data_train = []
data_train.append(X_all_train)
data_train.append(Y_all_train)
data_train.append(X_per_cycle_train)
data_train.append(Y_per_cycle_train)
    
data_train = np.array(data_train)
print("saved data shape: ", data_train.shape)
np.save('./wfv_train'+file_path, data_train)
print()

#### TEST

## 1.read from excel
test_data_x = pd.read_excel('../'+file_path, sheet_name='WFV testdata', usecols="B:E", nrows=num_total_test[1]+1, header=header)
test_data_y = pd.read_excel('../'+file_path, sheet_name='WFV testdata', usecols="F:M", nrows=num_total_test[1]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_test , Y_all_test = np.zeros((num_total_test[1], num_input[1]-2)), np.zeros((num_total_test[1], num_output))
X_per_cycle_test, Y_per_cycle_test = np.zeros((num_of_cycle_test[1], num_input[1]-2)), np.zeros((num_of_cycle_test[1], num_output))

## 3. DATA_X DATA_Y preprocessing
test_data_y = test_data_y.drop('Idlo', axis=1)
test_data_y = test_data_y.drop('Idhi', axis=1)

## 4. X_per_cycle, Y_all
for i in range(num_of_cycle_test[1]):
    X_per_cycle_test[i] = test_data_x[i*num_in_cycle_test:i*num_in_cycle_test+1].values
    
Y_all_test = test_data_y.values    

## 5. X_all, Y_per_cycle
for i in range(num_of_cycle_test[1]):
#     print(i*num_in_cycle_test, (i+1)*num_in_cycle_test)
#     print(X_per_cycle_test[i])
#     print(np.reshape(X_per_cycle_test[i], (1,3)).shape)
    X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test] = np.repeat(np.reshape(X_per_cycle_test[i], (1,3)), num_in_cycle_test, axis=0)
#     print(X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test])

    Y_per_cycle_test[i] = np.mean(Y_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test], axis=0)

## 6. 인위적으로 one-hot 넣어주기
X_all_test = np.hstack((X_all_test, np.ones((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.ones((X_per_cycle_test.shape[0], 1))))

X_all_test = np.hstack((X_all_test, np.zeros((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.zeros((X_per_cycle_test.shape[0], 1))))    
    
# for i in range(X_all_test.shape[0]):
#     print(X_all_test[i])
#     print(Y_all_test[i])
    
    
print("============ TEST Data load =============")
print()
print("X data shape: ", X_all_test.shape, "X per cycle data shape:", X_per_cycle_test.shape)
print("Y data shape: ", Y_all_test.shape, "Y per cycle data shape:", Y_per_cycle_test.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_test)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_test)))  
print()
print("============ TRAIN Data save =============")
print()
data_test = []
data_test.append(X_all_test)
data_test.append(Y_all_test)
data_test.append(X_per_cycle_test)
data_test.append(Y_per_cycle_test)
    
data_test = np.array(data_test)
print("saved data shape: ", data_test.shape)
np.save('./wfv_test'+file_path, data_test)
print()


# # RDF+WFV  
    

              Ioff  Vtlin  Vtsat     Idlin     Idsat      SS
0     2.703000e-11  0.290  0.283  0.000032  0.000059  62.901
1     1.186000e-11  0.321  0.299  0.000032  0.000061  62.270
2     3.794000e-12  0.356  0.350  0.000030  0.000052  64.063
3     1.247000e-12  0.386  0.361  0.000028  0.000050  62.222
4     1.319000e-12  0.373  0.363  0.000029  0.000047  62.514
...            ...    ...    ...       ...       ...     ...
2496  3.999000e-12  0.337  0.333  0.000027  0.000051  62.634
2497  4.579000e-12  0.332  0.322  0.000028  0.000057  62.099
2498  3.646000e-12  0.339  0.331  0.000027  0.000053  62.261
2499  3.880000e-12  0.339  0.328  0.000027  0.000055  61.992
2500           NaN    NaN    NaN       NaN       NaN     NaN

[2501 rows x 6 columns]
============ TRAIN Data load =============

X data shape:  (2500, 6) X per cycle data shape: (50, 6)
Y data shape:  (2500, 6) Y per cycle data shape: (50, 6)
any nan in X?:  []
any nan in Y?:  []

============ TRAIN Data save =============

sa

In [83]:
##### train
file_path = 'wfv_train2020_RDFWFV_20201029_V08.xlsx'

data = np.load(file_path+'.npy', allow_pickle=True)

X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

for i in range(Y_all.shape[0]):
    print(Y_all[i])

# test    
test_file_path = 'wfv_test2020_RDFWFV_20201029_V08.xlsx'

test_data = np.load(test_file_path+'.npy', allow_pickle=True)

test_X_all, test_Y_all, test_X_per_cycle, test_Y_per_cycle = test_data[0], test_data[1], test_data[2], test_data[3]

print(test_data[0].shape, test_data[1].shape, test_data[2].shape, test_data[3].shape)

for i in range(test_Y_all.shape[0]):
    print(test_Y_all[i])

(2500, 6) (2500, 6) (50, 6) (50, 6)
[2.7030e-11 2.9000e-01 2.8300e-01 3.2220e-05 5.8510e-05 6.2901e+01]
[1.186e-11 3.210e-01 2.990e-01 3.187e-05 6.053e-05 6.227e+01]
[3.7940e-12 3.5600e-01 3.5000e-01 3.0350e-05 5.2050e-05 6.4063e+01]
[1.2470e-12 3.8600e-01 3.6100e-01 2.8460e-05 4.9920e-05 6.2222e+01]
[1.3190e-12 3.7300e-01 3.6300e-01 2.8770e-05 4.7440e-05 6.2514e+01]
[2.9460e-12 3.4900e-01 3.4200e-01 3.0490e-05 5.1760e-05 6.2591e+01]
[1.654e-12 3.690e-01 3.590e-01 2.961e-05 4.989e-05 6.302e+01]
[1.0580e-10 2.5800e-01 2.4100e-01 3.5220e-05 7.4250e-05 6.2615e+01]
[2.4470e-11 2.9200e-01 2.8000e-01 3.4290e-05 6.5080e-05 6.2403e+01]
[2.8100e-11 2.9000e-01 2.8400e-01 3.3530e-05 6.2020e-05 6.3251e+01]
[3.4990e-13 4.0300e-01 3.9300e-01 2.8480e-05 4.5600e-05 6.2181e+01]
[7.3910e-12 3.2400e-01 3.2000e-01 3.0300e-05 5.5680e-05 6.3174e+01]
[3.1020e-11 2.9100e-01 2.7300e-01 3.2660e-05 6.3740e-05 6.2115e+01]
[2.1460e-11 3.2100e-01 2.8200e-01 3.1510e-05 6.2740e-05 6.2188e+01]
[5.338e-11 2.700e-01 2.6

[3.0250e-11 2.8300e-01 2.7700e-01 7.4020e-06 2.0070e-05 6.1496e+01]
[8.1880e-12 3.2500e-01 3.1900e-01 6.8370e-06 1.6900e-05 6.1572e+01]
[8.9060e-14 4.3300e-01 4.2600e-01 6.3320e-06 1.4320e-05 6.0944e+01]
[5.8670e-12 3.3300e-01 3.2900e-01 6.6370e-06 1.7060e-05 6.1599e+01]
[2.577e-11 3.070e-01 2.800e-01 7.081e-06 1.931e-05 6.141e+01]
[8.4000e-12 3.6900e-01 3.1200e-01 6.8720e-06 1.9500e-05 6.1519e+01]
[3.4650e-11 2.8700e-01 2.7700e-01 7.3840e-06 1.9570e-05 6.1667e+01]
[8.1720e-13 3.8700e-01 3.6800e-01 6.7700e-06 1.6310e-05 6.0608e+01]
[2.2680e-11 2.9700e-01 2.9500e-01 7.0700e-06 1.8060e-05 6.2348e+01]
[1.2870e-13 4.2000e-01 4.1500e-01 6.5770e-06 1.5660e-05 6.1022e+01]
[2.6330e-11 2.9700e-01 2.7800e-01 7.1380e-06 2.0030e-05 6.1023e+01]
[2.9510e-11 2.9400e-01 2.8400e-01 6.8800e-06 1.7290e-05 6.1322e+01]
[9.8490e-14 4.3000e-01 4.2000e-01 6.4320e-06 1.5680e-05 6.0764e+01]
[2.2630e-13 4.1600e-01 4.1500e-01 6.4420e-06 1.4580e-05 6.1974e+01]
[1.3090e-11 3.3600e-01 2.9800e-01 6.8800e-06 1.8820e-0

[3.0750e-12 3.4500e-01 3.3900e-01 1.2420e-05 3.1910e-05 6.1954e+01]
[2.7450e-12 3.4700e-01 3.4000e-01 1.2380e-05 3.1170e-05 6.1579e+01]
[3.5910e-12 3.3800e-01 3.2600e-01 1.2690e-05 3.4600e-05 6.1334e+01]
[1.9380e-12 3.5600e-01 3.4900e-01 1.2380e-05 3.0330e-05 6.1783e+01]
[2.3720e-12 3.5100e-01 3.4400e-01 1.2570e-05 3.3030e-05 6.1689e+01]
[1.7210e-12 3.6600e-01 3.5100e-01 1.2370e-05 3.0030e-05 6.1955e+01]
[5.4880e-12 3.3200e-01 3.2400e-01 1.2460e-05 3.0880e-05 6.2208e+01]
[1.2400e-12 3.6300e-01 3.5800e-01 1.2800e-05 3.2770e-05 6.1904e+01]
[2.3630e-12 3.5200e-01 3.4300e-01 1.2350e-05 3.0600e-05 6.1742e+01]
[5.7840e-12 3.2800e-01 3.1500e-01 1.2630e-05 3.2770e-05 6.1385e+01]
[2.7420e-12 3.4000e-01 3.3500e-01 1.2520e-05 3.2360e-05 6.1387e+01]
[5.0380e-12 3.3300e-01 3.2300e-01 1.2550e-05 3.2770e-05 6.1572e+01]
[1.6290e-12 3.6100e-01 3.5800e-01 1.2100e-05 2.9220e-05 6.2328e+01]
[3.4730e-12 3.3900e-01 3.3600e-01 1.2700e-05 3.1400e-05 6.2546e+01]
[3.4600e-12 3.4000e-01 3.3200e-01 1.2430e-05 3.1

### 3. RDF+WFV ( train + test )

In [85]:
# file_path == '2020_RDFWFV_20201029_V08.xlsx':
#     num_input = [5, 6, 6] # RDF, WFV, RDF+WFV
#     num_output = 6
#     num_in_cycle_train = 50
#     num_in_cycle_test = 250
#     num_of_cycle_train = [50, 50, 100]
#     num_of_cycle_test = [2, 0, 2]
#     num_total_train = [x*num_in_cycle_train for x in num_of_cycle_train]
#     num_total_test = [x*num_in_cycle_test for x in num_of_cycle_test]
#     header = 0

file_path = '2020_RDFWFV_20201029_V08.xlsx'

#### TRAIN

## 1.read from excel
train_data_x = pd.read_excel('../'+file_path, sheet_name='RDFWFV data', usecols="C:F", nrows=num_total_train[2]+1, header=header)
train_data_y = pd.read_excel('../'+file_path, sheet_name='RDFWFV data', usecols="G:N", nrows=num_total_train[2]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_train , Y_all_train = np.zeros((num_total_train[2], num_input[2]-2)), np.zeros((num_total_train[2], num_output))
X_per_cycle_train, Y_per_cycle_train = np.zeros((num_of_cycle_train[2], num_input[2]-2)), np.zeros((num_of_cycle_train[2], num_output))

## 3. DATA_X DATA_Y preprocessing
# Y: IDLO, IDHI
train_data_y = train_data_y.drop('Idlo', axis=1)
train_data_y = train_data_y.drop('Idhi', axis=1)

print(train_data_y)

## 4. X_per_cycle
for i in range(num_of_cycle_train[2]):
#     print(i*num_in_cycle_train, i*num_in_cycle_train+1)
    X_per_cycle_train[i] = train_data_x[i*num_in_cycle_train:i*num_in_cycle_train+1].values
#     print(X_per_cycle_train[i])

## 5. X_all
X_all_train = np.repeat(X_per_cycle_train,num_in_cycle_train,axis=0)


## 6. 인위적으로 one-hot 넣어주기
X_all_train = np.hstack((X_all_train, np.ones((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.ones((X_per_cycle_train.shape[0], 1))))

X_all_train = np.hstack((X_all_train, np.zeros((X_all_train.shape[0], 1))))
X_per_cycle_train = np.hstack((X_per_cycle_train, np.zeros((X_per_cycle_train.shape[0], 1))))


## 7. Y_all
for i in range(num_of_cycle_train[2]):
#     print(i*num_in_cycle_train,(i+1)*num_in_cycle_train)
    Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train] = train_data_y[i*num_in_cycle_train:(i+1)*num_in_cycle_train].values
#     print(Y_all_train[i*num_in_cycle_train])

## 8. Y_per_cycle    
for i in range(num_of_cycle_train[2]):
    Y_per_cycle_train[i] = np.mean(Y_all_train[i*num_in_cycle_train:(i+1)*num_in_cycle_train],axis=0)
#     print(i, Y_per_cycle_train[i])

print("============ TRAIN Data load =============")
print()
print("X data shape: ", X_all_train.shape, "X per cycle data shape:", X_per_cycle_train.shape)
print("Y data shape: ", Y_all_train.shape, "Y per cycle data shape:", Y_per_cycle_train.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_train)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_train)))  
print()
print("============ TRAIN Data save =============")
print()
data_train = []
data_train.append(X_all_train)
data_train.append(Y_all_train)
data_train.append(X_per_cycle_train)
data_train.append(Y_per_cycle_train)
    
data_train = np.array(data_train)
print("saved data shape: ", data_train.shape)
np.save('./rdfwfv_train'+file_path, data_train)
print()

#### TEST

## 1.read from excel
test_data_x = pd.read_excel('../'+file_path, sheet_name='RDFWFV testdata', usecols="B:E", nrows=num_total_test[2]+1, header=header)
test_data_y = pd.read_excel('../'+file_path, sheet_name='RDFWFV testdata', usecols="F:M", nrows=num_total_test[2]+1, header=header)

## 2.one-hot encoding (나중에 1, 0 을 인위적으로 넣어주기)
X_all_test , Y_all_test = np.zeros((num_total_test[2], num_input[2]-2)), np.zeros((num_total_test[2], num_output))
X_per_cycle_test, Y_per_cycle_test = np.zeros((num_of_cycle_test[2], num_input[2]-2)), np.zeros((num_of_cycle_test[2], num_output))

## 3. DATA_X DATA_Y preprocessing
test_data_y = test_data_y.drop('Idlo', axis=1)
test_data_y = test_data_y.drop('Idhi', axis=1)

## 4. X_per_cycle, Y_all
for i in range(num_of_cycle_test[2]):
    X_per_cycle_test[i] = test_data_x[i*num_in_cycle_test:i*num_in_cycle_test+1].values
    
Y_all_test = test_data_y.values    

## 5. X_all, Y_per_cycle
for i in range(num_of_cycle_test[2]):
#     print(i*num_in_cycle_test, (i+1)*num_in_cycle_test)
#     print(X_per_cycle_test[i])
#     print(np.reshape(X_per_cycle_test[i], (1,3)).shape)
    X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test] = np.repeat(np.reshape(X_per_cycle_test[i], (1,4)), num_in_cycle_test, axis=0)
#     print(X_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test])

    Y_per_cycle_test[i] = np.mean(Y_all_test[i*num_in_cycle_test:(i+1)*num_in_cycle_test], axis=0)

## 6. 인위적으로 one-hot 넣어주기
X_all_test = np.hstack((X_all_test, np.ones((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.ones((X_per_cycle_test.shape[0], 1))))

X_all_test = np.hstack((X_all_test, np.zeros((X_all_test.shape[0], 1))))
X_per_cycle_test = np.hstack((X_per_cycle_test, np.zeros((X_per_cycle_test.shape[0], 1))))    
    
# for i in range(X_all_test.shape[0]):
#     print(X_all_test[i])
#     print(Y_all_test[i])
    
    
print("============ TEST Data load =============")
print()
print("X data shape: ", X_all_test.shape, "X per cycle data shape:", X_per_cycle_test.shape)
print("Y data shape: ", Y_all_test.shape, "Y per cycle data shape:", Y_per_cycle_test.shape)  
print("any nan in X?: ", np.argwhere(np.isnan(X_all_test)))
print("any nan in Y?: ", np.argwhere(np.isnan(Y_all_test)))  
print()
print("============ TRAIN Data save =============")
print()
data_test = []
data_test.append(X_all_test)
data_test.append(Y_all_test)
data_test.append(X_per_cycle_test)
data_test.append(Y_per_cycle_test)
    
data_test = np.array(data_test)
print("saved data shape: ", data_test.shape)
np.save('./rdfwfv_test'+file_path, data_test)
print()


# # RDF+WFV  
    

              Ioff  Vtlin  Vtsat     Idlin     Idsat      SS
0     3.570000e-11  0.285  0.277  0.000024  0.000057  63.283
1     1.651000e-11  0.316  0.293  0.000024  0.000056  62.388
2     1.117000e-11  0.338  0.325  0.000023  0.000051  65.969
3     1.916000e-12  0.379  0.354  0.000022  0.000046  63.341
4     2.597000e-12  0.357  0.347  0.000023  0.000049  63.126
...            ...    ...    ...       ...       ...     ...
4995  3.492000e-12  0.340  0.326  0.000009  0.000027  60.761
4996  2.046000e-12  0.355  0.345  0.000008  0.000022  61.140
4997  2.312000e-12  0.356  0.347  0.000008  0.000024  61.816
4998  1.211000e-11  0.310  0.302  0.000010  0.000030  61.313
4999  3.424000e-12  0.360  0.349  0.000009  0.000026  63.035

[5000 rows x 6 columns]
============ TRAIN Data load =============

X data shape:  (5000, 6) X per cycle data shape: (100, 6)
Y data shape:  (5000, 6) Y per cycle data shape: (100, 6)
any nan in X?:  []
any nan in Y?:  []

============ TRAIN Data save =============



In [86]:
##### train
file_path = 'rdfwfv_train2020_RDFWFV_20201029_V08.xlsx'

data = np.load(file_path+'.npy', allow_pickle=True)

X_all, Y_all, X_per_cycle, Y_per_cycle = data[0], data[1], data[2], data[3]

print(data[0].shape, data[1].shape, data[2].shape, data[3].shape)

for i in range(Y_all.shape[0]):
    print(Y_all[i])

# test    
test_file_path = 'rdfwfv_test2020_RDFWFV_20201029_V08.xlsx'

test_data = np.load(test_file_path+'.npy', allow_pickle=True)

test_X_all, test_Y_all, test_X_per_cycle, test_Y_per_cycle = test_data[0], test_data[1], test_data[2], test_data[3]

print(test_data[0].shape, test_data[1].shape, test_data[2].shape, test_data[3].shape)

for i in range(test_Y_all.shape[0]):
    print(test_Y_all[i])

(5000, 6) (5000, 6) (100, 6) (100, 6)
[3.5700e-11 2.8500e-01 2.7700e-01 2.4430e-05 5.7230e-05 6.3283e+01]
[1.6510e-11 3.1600e-01 2.9300e-01 2.3700e-05 5.6060e-05 6.2388e+01]
[1.1170e-11 3.3800e-01 3.2500e-01 2.3180e-05 5.1100e-05 6.5969e+01]
[1.9160e-12 3.7900e-01 3.5400e-01 2.1630e-05 4.6370e-05 6.3341e+01]
[2.5970e-12 3.5700e-01 3.4700e-01 2.3220e-05 4.8530e-05 6.3126e+01]
[5.1690e-12 3.4000e-01 3.3200e-01 2.3740e-05 5.2030e-05 6.4033e+01]
[2.1280e-12 3.6500e-01 3.5400e-01 2.3860e-05 4.9420e-05 6.3262e+01]
[1.9850e-10 2.4200e-01 2.2800e-01 2.7770e-05 7.3630e-05 6.3776e+01]
[5.3330e-11 2.7700e-01 2.6500e-01 2.5750e-05 6.0930e-05 6.3092e+01]
[3.9620e-11 2.8400e-01 2.7700e-01 2.5330e-05 5.9300e-05 6.3403e+01]
[3.4120e-13 4.0900e-01 3.9600e-01 2.0560e-05 4.0210e-05 6.2841e+01]
[1.1660e-11 3.1700e-01 3.1100e-01 2.3270e-05 5.3120e-05 6.3704e+01]
[4.5650e-11 2.7700e-01 2.6300e-01 2.6480e-05 6.5540e-05 6.2148e+01]
[3.0710e-11 3.0000e-01 2.7400e-01 2.4430e-05 5.9970e-05 6.2568e+01]
[7.9300e-1

[2.250e-12 3.530e-01 3.480e-01 8.964e-06 2.522e-05 6.178e+01]
[3.5100e-12 3.3800e-01 3.3400e-01 8.5770e-06 2.4250e-05 6.1711e+01]
[3.3900e-12 3.4000e-01 3.3200e-01 8.5000e-06 2.5490e-05 6.1341e+01]
[7.4490e-12 3.2800e-01 3.1500e-01 8.4610e-06 2.2570e-05 6.1369e+01]
[5.6350e-12 3.2500e-01 3.1700e-01 8.8080e-06 2.6830e-05 6.0788e+01]
[1.5130e-12 3.6400e-01 3.5000e-01 8.5290e-06 2.4650e-05 6.1433e+01]
[3.4800e-12 3.3800e-01 3.2900e-01 8.1520e-06 2.4620e-05 6.1028e+01]
[1.6870e-12 3.5700e-01 3.4600e-01 8.4270e-06 2.3750e-05 6.0858e+01]
[6.9690e-12 3.2100e-01 3.1400e-01 8.8670e-06 2.6790e-05 6.1267e+01]
[4.4870e-13 3.8800e-01 3.8100e-01 7.9020e-06 2.1890e-05 6.1056e+01]
[2.1000e-12 3.5600e-01 3.4000e-01 8.2760e-06 2.4090e-05 6.1021e+01]
[3.3970e-12 3.4100e-01 3.2700e-01 8.5950e-06 2.7730e-05 6.0906e+01]
[2.5170e-12 3.4700e-01 3.3800e-01 9.0760e-06 2.7230e-05 6.1054e+01]
[1.1730e-12 3.6700e-01 3.5900e-01 8.2200e-06 2.2710e-05 6.1522e+01]
[4.1440e-12 3.3400e-01 3.2700e-01 8.3250e-06 2.5210e-0

[6.1570e-11 2.6700e-01 2.5600e-01 2.1480e-05 5.9670e-05 6.2399e+01]
[1.6530e-12 3.6700e-01 3.5100e-01 1.8720e-05 4.3620e-05 6.1919e+01]
[2.2400e-11 3.0600e-01 2.9300e-01 1.9790e-05 4.7440e-05 6.2913e+01]
[3.0780e-13 4.0600e-01 3.9800e-01 1.7640e-05 3.7480e-05 6.2285e+01]
[1.6640e-11 3.0400e-01 2.9400e-01 1.9120e-05 4.8610e-05 6.2134e+01]
[6.6080e-11 2.7000e-01 2.5800e-01 2.0670e-05 5.4080e-05 6.2635e+01]
[2.6690e-13 4.1200e-01 4.0000e-01 1.6880e-05 3.5650e-05 6.2175e+01]
[1.0420e-12 3.7600e-01 3.7000e-01 1.7820e-05 4.0690e-05 6.2779e+01]
[2.2200e-11 3.1800e-01 2.8400e-01 1.9600e-05 4.9470e-05 6.2077e+01]
[1.4410e-12 3.8100e-01 3.5600e-01 1.7800e-05 4.0140e-05 6.1641e+01]
[2.8140e-12 3.5600e-01 3.3800e-01 2.1680e-05 4.7440e-05 6.2459e+01]
[7.235e-12 3.360e-01 3.110e-01 1.915e-05 4.823e-05 6.223e+01]
[1.4550e-11 3.1100e-01 3.0600e-01 2.0220e-05 4.7750e-05 6.3147e+01]
[7.5960e-13 3.9200e-01 3.7500e-01 1.8820e-05 4.1700e-05 6.3148e+01]
[1.1580e-11 3.2000e-01 3.0800e-01 2.2010e-05 4.7390e-0

[2.4360e-11 3.1300e-01 2.8100e-01 2.2160e-05 5.4400e-05 6.2246e+01]
[6.7280e-11 2.6500e-01 2.5400e-01 2.5690e-05 6.4210e-05 6.2501e+01]
[2.2960e-12 3.6000e-01 3.4600e-01 2.3430e-05 4.7660e-05 6.2195e+01]
[2.5480e-11 3.0600e-01 2.8900e-01 2.1880e-05 5.0530e-05 6.3091e+01]
[3.5610e-13 4.0500e-01 3.9700e-01 2.0770e-05 4.0390e-05 6.2545e+01]
[1.563e-11 3.090e-01 2.990e-01 2.190e-05 5.127e-05 6.292e+01]
[7.3730e-11 2.6800e-01 2.5700e-01 2.4650e-05 5.9640e-05 6.2985e+01]
[3.523e-13 4.100e-01 3.950e-01 2.122e-05 4.062e-05 6.222e+01]
[1.1720e-12 3.7300e-01 3.6600e-01 2.1620e-05 4.4950e-05 6.2571e+01]
[2.8600e-11 3.0500e-01 2.7800e-01 2.3320e-05 5.3860e-05 6.2278e+01]
[1.6110e-12 3.8000e-01 3.5400e-01 1.9980e-05 4.2790e-05 6.1902e+01]
[6.4150e-12 3.3500e-01 3.2000e-01 2.3860e-05 5.3450e-05 6.3062e+01]
[8.3860e-12 3.3300e-01 3.0800e-01 2.1820e-05 5.2390e-05 6.2369e+01]
[1.420e-11 3.120e-01 3.060e-01 2.147e-05 4.883e-05 6.339e+01]
[3.1430e-12 3.4800e-01 3.3700e-01 2.3440e-05 5.0160e-05 6.2182e+01

[8.5440e-12 3.1500e-01 3.0700e-01 8.6890e-06 2.3840e-05 6.1028e+01]
[8.5120e-12 3.2300e-01 3.1800e-01 8.6770e-06 2.4510e-05 6.2038e+01]
[3.2410e-12 3.4100e-01 3.3800e-01 9.2110e-06 2.6870e-05 6.1841e+01]
[6.848e-12 3.240e-01 3.160e-01 8.811e-06 2.454e-05 6.167e+01]
[1.6800e-12 3.5400e-01 3.4800e-01 8.5110e-06 2.3530e-05 6.0756e+01]
[5.6730e-12 3.3600e-01 3.1500e-01 8.6740e-06 2.6950e-05 6.0971e+01]
[1.9510e-11 2.9300e-01 2.8500e-01 8.7560e-06 2.7970e-05 6.1296e+01]
[5.6540e-13 3.8200e-01 3.7600e-01 8.4800e-06 2.2760e-05 6.1167e+01]
[9.4060e-13 3.7700e-01 3.7600e-01 8.3850e-06 2.1060e-05 6.2289e+01]
[4.9910e-13 3.9400e-01 3.8900e-01 8.8190e-06 2.3660e-05 6.2258e+01]
[2.7890e-12 3.4500e-01 3.3400e-01 8.6780e-06 2.5300e-05 6.1002e+01]
[1.6090e-11 3.0800e-01 2.9500e-01 8.8380e-06 2.5540e-05 6.1709e+01]
[1.1410e-12 3.7100e-01 3.5900e-01 8.6600e-06 2.4910e-05 6.1278e+01]
[5.5190e-13 3.8800e-01 3.8100e-01 8.7910e-06 2.4610e-05 6.2279e+01]
[3.7790e-12 3.5100e-01 3.3300e-01 8.5120e-06 2.5360e-0

[8.3370e-12 3.1400e-01 3.0700e-01 5.9860e-06 1.6290e-05 6.0648e+01]
[1.1890e-12 3.7900e-01 3.6400e-01 5.2960e-06 1.2390e-05 6.0944e+01]
[3.8770e-12 3.5500e-01 3.3300e-01 5.3130e-06 1.4070e-05 6.0694e+01]
[6.954e-12 3.340e-01 3.300e-01 5.685e-06 1.447e-05 6.183e+01]
[1.2410e-13 4.2500e-01 4.1900e-01 5.2360e-06 1.2320e-05 6.1023e+01]
[4.1140e-12 3.4200e-01 3.3100e-01 5.4530e-06 1.5420e-05 6.1193e+01]
[5.6620e-13 3.9200e-01 3.8900e-01 5.4230e-06 1.2530e-05 6.2402e+01]
[7.8210e-13 3.7900e-01 3.7700e-01 5.8230e-06 1.3720e-05 6.1749e+01]
[8.6850e-13 3.7400e-01 3.7100e-01 5.4120e-06 1.2730e-05 6.1418e+01]
[6.6260e-13 3.8600e-01 3.7400e-01 5.7100e-06 1.4290e-05 6.0927e+01]
[3.7570e-12 3.4800e-01 3.3200e-01 6.0630e-06 1.6540e-05 6.1144e+01]
[1.9760e-11 2.9900e-01 2.8700e-01 5.8830e-06 1.7140e-05 6.1203e+01]
[8.2770e-13 3.7100e-01 3.6600e-01 5.8730e-06 1.4980e-05 6.0567e+01]
[1.6740e-11 2.9900e-01 2.9000e-01 6.5910e-06 1.8350e-05 6.0692e+01]
[1.1280e-12 3.7200e-01 3.6900e-01 6.1270e-06 1.4510e-0

# 검증의 시간

In [92]:
# 혼돈의 시작

file_path1 = '2020_LER_20201021_testset.xlsx'
file_path2 = '2020_LER_20200804_V006.xlsx'

file1 = np.load(file_path1+'.npy', allow_pickle=True)
file2 = np.load(file_path2+'.npy', allow_pickle=True)

X_all_1, Y_all_1, X_per_cycle_1, Y_per_cycle_1 = file1[0], file1[1], file1[2], file1[3]
X_all_2, Y_all_2, X_per_cycle_2, Y_per_cycle_2 = file2[0], file2[1], file2[2], file2[3]

X_per_cycle_2_test = X_per_cycle_2[85:]

new_factor = 2
old_factor = 7

print(X_per_cycle_1)
print(X_per_cycle_2_test.shape)

print(X_per_cycle_1[new_factor])
print(X_per_cycle_2_test[old_factor])

 


# for i in range(5):
#     print(X_per_cycle_1[i])
    
# # print(X_per_cycle_2_test)
# for j in range(15):
#     print(X_per_cycle_2_test[i])

[[  0.62484672  17.00743225 173.85718891   1.           0.        ]
 [  0.55654727  80.91905766  80.56986979   1.           0.        ]
 [  0.50466944  48.62398816  67.99380535   1.           0.        ]
 [  0.56045148  25.42868151  69.39740975   1.           0.        ]
 [  0.63730798  69.14860261  65.33037708   1.           0.        ]]
(15, 5)
[ 0.50466944 48.62398816 67.99380535  1.          0.        ]
[ 0.50466944 48.62398816 67.99380535  1.          0.        ]
