In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

%matplotlib inline

In [68]:
from sklearn.utils import shuffle

shuffle_idx = shuffle(np.arange(10), random_state=2)
print(shuffle_idx)

labels = shuffle(np.arange(9), random_state=3)
print(labels)

print(shuffle_idx[labels])

a = [0,0,1,1,2,2,3,3,4,4,5,5]
start_point = []
end_point = []
c = []
for i in range(6):
    start_point.append(np.argmin(a<i))
    end_point.append(np.argmax(a>(i)))
    c.append([])

start_point
    
self.end_point[-1] = len(labels)


[4 1 5 0 7 2 3 6 9 8]
[6 2 7 4 5 0 3 1 8]
[3 5 6 7 2 4 0 1 9]


TypeError: '<' not supported between instances of 'list' and 'int'

In [74]:
a = []
for i in range(3):
    a += range(100*i-i*10, 100*i)

print(a)
"""
for i in range(10):
    end = self.end_point[self.start + i]
                start = self.start_point[self.start + i]
                self.validation_buffer += range(end-val_per_class, end)
                self.tr_idx += range(start, end-val_per_class)
"""

[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


'\nfor i in range(10):\n    end = self.end_point[self.start + i]\n                start = self.start_point[self.start + i]\n                self.validation_buffer += range(end-val_per_class, end)\n                self.tr_idx += range(start, end-val_per_class)\n'

In [6]:
result_dict = {}

name = 'date_20200811_datatype_n_model_mlp_gan1_seed_0_mean_lr_5e-05_g_lr_0.0001_d_lr_0.0005_mean_hidden_dim_100_gan_type_gan1_gan_hidden_dim_100_batch_32_epoch_1000_noise_100.mat'
result_dict = sio.loadmat(name)

print(result_dict)
train_loss = result_dict['train_loss']
val_loss = result_dict['val_loss']
p_real_train = result_dict['p_real_train']
p_fake_train = result_dict['p_fake_train']
p_real_val = result_dict['p_real_val']
p_fake_val = result_dict['p_fake_val']

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Aug 14 18:11:36 2020', '__version__': '1.0', '__globals__': [], 'train_loss': array([[array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        array([[None]], dtype=object), array([[None]], dtype=object),
        arra

In [31]:
result_dict = {}

name = 'date_20200811_datatype_n_model_mlp_gan1_seed_0_mean_lr_5e-05_g_lr_0.0001_d_lr_0.0005_mean_hidden_dim_100_gan_type_gan1_gan_hidden_dim_100_batch_32_epoch_1000_noise_100.npy'
result_dict = np.load(name, allow_pickle=True)

p_real_train = result_dict.item().get('p_real_train').numpy()
p_fake_train = result_dict.item().get('p_fake_train')
p_real_val = result_dict.item().get('p_real_val')
p_fake_val = result_dict.item().get('p_fake_val')

print(p_real_train)
#train_loss = result_dict['train_loss']
#val_loss = result_dict['val_loss']
#p_real_train = result_dict['p_real_train']
#p_fake_train = result_dict['p_fake_train']
#p_real_val = result_dict['p_real_val']
#p_fake_val = result_dict['p_fake_val']

AttributeError: 'list' object has no attribute 'numpy'

In [10]:
print(p_real_train)

[[array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array([[None]], dtype=object) array([[None]], dtype=object)
  array(